### ISSUE TITLE
Cannot find module 'async-repl/stubber'

### ISSUE THREAD

**Issue by fatkhanfauzi** [ownadi/async-repl#5]
Hi,
i found this issue when i was following your instruction for custom repl.

`> require('async-repl/stubber')
{ Error: Cannot find module 'async-repl/stubber'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' }`

any thought ?

**Comment by ownadi** [comment]
Do you use the most recent version of this package? This export has been introduced in 0.4.0
